//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int Id { get; set; }
        public Nullable<decimal> marks { get; set; }
        public string rollno { get; set; }
        public int ass_course_id { get; set; }
    
        public virtual assigned_course assigned_course { get; set; }
        public virtual student student { get; set; }
    }
}
