//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_CMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assigned_course> assigned_course { get; set; }
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<attendence> attendences { get; set; }
        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<degree> degrees { get; set; }
        public virtual DbSet<final> finals { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<mid> mids { get; set; }
        public virtual DbSet<quiz> quizs { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
