//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class course
    {

        public int id { get; set; }
        [Required]
        [DisplayName("Name")]
        [Remote("isCourseExist", "Admin", HttpMethod = "Get", ErrorMessage = "Such Course already exists!")]
        public string name { get; set; }
    }
}
