//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class degree
    {
        public degree()
        {
            this.students = new HashSet<student>();
            this.assigned_course = new HashSet<assigned_course>();
        }

        [DisplayName("Degree")]
        public string title { get; set; }

        public virtual ICollection<student> students { get; set; }
        public virtual ICollection<assigned_course> assigned_course { get; set; }
    }
}
