//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Teacher
    {
        public Teacher()
        {
            this.assigned_course = new HashSet<assigned_course>();
        }


        [DisplayName("Username")]
        [Required]
        [Remote("isExist", "Admin", HttpMethod = "Get", ErrorMessage = "Such username already exists!")]
        public string username { get; set; }

        [DisplayName("Teacher's Name")]
        [Required]
        public string name { get; set; }

        public virtual ICollection<assigned_course> assigned_course { get; set; }
    }
}
